//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PracticeTestEntities : DbContext
    {
        public PracticeTestEntities()
            : base("name=PracticeTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DesignationMaster> DesignationMasters { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<EmployeeMaster> EmployeeMasters { get; set; }
    }
}
